#!/bin/bash
#PBS -N h2pEigenstates
#PBS -l nodes=1:ppn=1
#PBS -j oe
#PBS -q xeon

export OMP_NUM_THREADS=1

JOB_DIR="/home/becker/cogo4490/Projects/H2+/1D/eigenstate"
cd $JOB_DIR
hostname
pwd

./eigenstatesBO input.cfg > result.log